;;; erc-nick-colors --- Adds colored nick support to ERC.
;;; Commentary:
;;; Stolen from emacs-wiki.
;;; Code:
(require 'rc)
(require 'packages)

(packages/define erc-nick-colors (erc)
	   ;; Pool of colors to use when coloring IRC nicks.
	   (defvar erc-nick-colors-list
	     '("green" "blue" "red"
	       "dark gray" "dark orange"
	       "dark magenta" "maroon"
	       "indian red" "black" "forest green"
	       "midnight blue" "dark violet")
	     "Pool of colors to use when coloring IRC nicks.")

	   (defvar erc-nick-colors-alist '()
	     "Override erc autogenerated colors for specific nicks.")

	   (defun erc-get-color-for-nick (nick)
	     "Gets a color for NICK. If NICK is in erc-nick-color-alist, use that color, else hash the nick and use a random color from the pool"
	     (or (cdr (assoc nick erc-nick-colors-alist))
		 (nth
		  (mod (string-to-number
			(substring (md5 (downcase nick)) 0 6) 16)
		       (length erc-nick-colors-list))
		  erc-nick-colors-list)))

	   (defun erc-put-color-on-nick ()
	     "Modifies the color of nicks according to erc-get-color-for-nick"
	     (save-excursion
	       (goto-char (point-min))
	       (if (looking-at "<\\([^>]*\\)>")
		   (let ((nick (match-string 1)))
		     (put-text-property (match-beginning 1) (match-end 1) 'face
					(cons 'foreground-color
					      (erc-get-color-for-nick nick)))))))

	   (add-hooks (erc-insert-modify-hook)
		      erc-put-color-on-nick))
;;; erc-nick-colors.el ends here
