;;; when-to-enable-evil --- Enable EVIL.
;;; Commentary:
;;; Autogenerated using custom mode, be careful rewriting this.
;;; Code:
(require 'rc)

(global-evil-leader-mode 1)
(evil-mode 1)
;;; when-to-enable-evil.el ends here
